version: "2"
services:
    ezgripper:
        build: docker
        container_name: ez_gripper
        environment:
            # to transport X11 application window 
            - DISPLAY
            - QT_X11_NO_MITSHM=1
        volumes:
            # to use devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ./catkin_ws:/root/catkin_ws
        privileged: true
        network_mode: host
        command: /bin/bash
